package tournament_trail.demo.security;

public enum Permission {
    TOURNAMENT_CREATE,
    TOURNAMENT_EDIT_OWN,
    TOURNAMENT_MODERATE,
    REGISTRATION_MANAGE,
    TRAVEL_GROUP_CREATE,
    TRAVEL_GROUP_MANAGE_OWN,
    COMMENT_CREATE,
    COMMENT_MODERATE,
    ORGANIZER_APPLICATION_REVIEW,
    USER_MANAGE
}
